import * as THREE from 'three';
import {createIcons,Maximize,Play,Pause,RotateCcw,Plus,X,ArrowUp,ArrowDown} from 'lucide';
import data from './hanon_units.json';
import {defaults,makeChart,judge} from './core.js';

const $=s=>document.querySelector(s), colors=['#93f7d0','#98dcff','#ffd789','#f9a7cd','#d5bdff','#ffaf96'];
let config=structuredClone({...defaults,transpose:'diatonic'});
try{const saved=JSON.parse(localStorage.getItem('hanon-six'));if(saved&&Array.isArray(saved.queue)&&saved.queue.every(id=>data[id])&&Array.isArray(saved.windows)&&saved.windows.length&&saved.windows.every((w,i)=>Number.isFinite(w.end)&&w.end>0&&(!i||w.end>saved.windows[i-1].end))&&saved.keys?.length===6)config={...config,...saved};}catch{}
const iconize=()=>createIcons({icons:{Maximize,Play,Pause,RotateCcw,Plus,X,ArrowUp,ArrowDown}});
function save(){localStorage.setItem('hanon-six',JSON.stringify(config));}
const keyName=k=>k==='Space'?'Space':k==='ShiftLeft'?'L Shift':k==='ShiftRight'?'R Shift':k.replace(/^Key|^Digit/,'');
let mode='setup',chart,elapsed=0,anchor=0,manual=false,audio,audioZero=0,musicIndex=0,beatIndex=0,voices=[],pausedAt=0,resumeUntil=0,combo=0,maxCombo=0,weight=0,counts=[],errors=[],resolved=0,captureKey=-1;
const held=new Set(),flashes=Array(6).fill(0),noteMeshes=new Map();

const scene=new THREE.Scene();scene.background=new THREE.Color('#080e11');scene.fog=new THREE.Fog('#080e11',26,68);
const camera=new THREE.PerspectiveCamera(48,1,.1,110);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('#stage').append(renderer.domElement);
const world=new THREE.Group();scene.add(world);
// All surfaces use the same cross-section, so outer notes and receptors follow the raised lanes.
function height(x){return Math.max(0,Math.abs(x)-2)*Math.tan(THREE.MathUtils.degToRad(config.wingAngle));}
function surface(x1,x2,z1,z2,color,y=.0,opacity=1){const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute([x1,height(x1)+y,z1,x2,height(x2)+y,z1,x2,height(x2)+y,z2,x1,height(x1)+y,z2],3));geo.setIndex([0,1,2,0,2,3]);geo.computeVertexNormals();const mesh=new THREE.Mesh(geo,new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,transparent:opacity<1,opacity}));world.add(mesh);return mesh;}
const receptors=[],lit=[];
for(let i=0;i<6;i++){let x=i-3;surface(x+.025,x+.975,-58,3,i===0?'#283349':i===5?'#402b3c':i%2?'#162d30':'#1a3334');surface(x+.025,x+.045,-58,3,i===0?'#b8b5ff':i===5?'#f3a0bc':'#6a9b96',.006,.45);receptors.push(surface(x+.055,x+.945,-.055,.055,i===0?'#b8b5ff':i===5?'#f3a0bc':'#91f4d7',.025));lit.push(surface(x+.03,x+.97,-5,.4,i===0?'#ac9dff':i===5?'#ffa0c0':'#86ffd8',.018,0));}
for(let z=-55;z<3;z+=3)surface(-3,3,z,z+.012,'#8abba9',.007,.12);
for(const side of [-1,1]){for(let i=0;i<13;i++){const mesh=new THREE.Mesh(new THREE.OctahedronGeometry(.10),new THREE.MeshBasicMaterial({color:side<0?'#587e85':'#956076',wireframe:true}));mesh.position.set(side*(3.5+i*.09),.4,-i*3);world.add(mesh);}}
const noteGeo=new THREE.BoxGeometry(.86,.07,.22),noteMaterials=Array.from({length:6},(_,i)=>new THREE.MeshBasicMaterial({color:i===0?'#c3b6ff':i===5?'#ffa8c9':'#58b5ff'}));
const surfaces=world.children.filter(mesh=>mesh.geometry.attributes.position.count===4);
const surfaceOffsets=new Map(surfaces.map(mesh=>[mesh,mesh.geometry.attributes.position.getY(0)-height(mesh.geometry.attributes.position.getX(0))]));
function updateTrack(){for(const mesh of surfaces){const p=mesh.geometry.attributes.position;for(let i=0;i<p.count;i++)p.setY(i,height(p.getX(i))+surfaceOffsets.get(mesh));p.needsUpdate=true;mesh.geometry.computeVertexNormals();mesh.geometry.computeBoundingSphere();}resize();$('#slope-value').textContent=`${config.slope}°`;$('#wingAngle-value').textContent=`${config.wingAngle}°`;}
function project(lane,z=0,y=.15){return new THREE.Vector3(lane-2.5,height(lane-2.5)+y,z).project(camera);}
function resize(){const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.zoom=Math.min(1,(w/h)/.95);const angle=THREE.MathUtils.degToRad(config.slope),distance=19.12+Math.max(0,config.slope-16)*.4;camera.position.set(0,Math.sin(angle)*distance,Math.cos(angle)*distance-10);camera.lookAt(0,0,-10);camera.setViewOffset(w,h,mode==='setup'&&w>850?w*.16:0,w/h<.8?-h*.17:0,w,h);camera.updateProjectionMatrix();camera.updateMatrixWorld();positionLabels();}
function positionLabels(){const w=innerWidth,h=innerHeight;$('#lane-labels').replaceChildren(...config.keys.map((key,i)=>{const e=document.createElement('span'),p=project(i,.9,.12);e.textContent=keyName(key);e.style.left=`${(p.x+1)*w/2}px`;e.style.top=`${(1-p.y)*h/2}px`;return e;}));}
addEventListener('resize',resize);

function renderQueue(){const lib=$('#library');lib.replaceChildren(...Object.keys(data).map(id=>{const b=document.createElement('button');b.textContent=id.padStart(2,'0');b.title=`添加哈农 ${id}`;b.classList.toggle('selected',config.queue.includes(id));b.onclick=()=>{if(config.queue.length>=100)return showError('最多编排 100 个练习');config.queue.push(id);changed();};return b;}));$('#queue').replaceChildren(...config.queue.map((id,i)=>{const li=document.createElement('li');li.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong>Hanon ${id.padStart(2,'0')}</strong><button title="上移" ${i===0?'disabled':''}><i data-lucide="arrow-up"></i></button><button title="下移" ${i===config.queue.length-1?'disabled':''}><i data-lucide="arrow-down"></i></button><button title="移除"><i data-lucide="x"></i></button>`;const buttons=li.querySelectorAll('button');buttons[0].onclick=()=>{[config.queue[i-1],config.queue[i]]=[config.queue[i],config.queue[i-1]];changed();};buttons[1].onclick=()=>{[config.queue[i+1],config.queue[i]]=[config.queue[i],config.queue[i+1]];changed();};buttons[2].onclick=()=>{config.queue.splice(i,1);changed();};return li;}));$('#queue-count').textContent=`${config.queue.length} 个练习`;iconize();}
function updateSummary(){const c=makeChart(data,config);$('#note-count').textContent=`${c.notes.length.toLocaleString()} NOTES`;const seconds=Math.ceil(c.end/1000);$('#duration').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('#start-meta').textContent=`${config.bpm} BPM`;$('#start').disabled=!c.notes.length;$('#speed-value').textContent=`${config.speed.toFixed(1)} u/s`;}
function changed(){save();renderQueue();updateSummary();}
function showError(message=''){$('#error').textContent=message;}
function renderWindows(){const axis=$('#axis'),zoom=Number($('#zoom').value);axis.replaceChildren();let start=0;for(let i=0;i<config.windows.length;i++){const w=config.windows[i],c=colors[i%colors.length];if(start<zoom){const segment=document.createElement('button');segment.className='axis-range';segment.style.cssText=`left:${start/zoom*100}%;width:${(Math.min(w.end,zoom)-start)/zoom*100}%;--c:${c}`;segment.textContent=w.name;segment.title=`${start}–${w.end} ms`;segment.onclick=()=>$('#windows').children[i].querySelector('input').focus();axis.append(segment);}if(w.end<=zoom){const point=document.createElement('button');point.className='axis-point';point.title=`拖动 ${w.end} ms 端点`;point.style.left=`${w.end/zoom*100}%`;point.innerHTML=`<span>${w.end}</span>`;point.onpointerdown=e=>{e.preventDefault();point.setPointerCapture(e.pointerId);};point.onpointermove=e=>{if(!point.hasPointerCapture(e.pointerId))return;const rect=axis.getBoundingClientRect();const val=Math.round((e.clientX-rect.left)/rect.width*zoom);w.end=Math.max((config.windows[i-1]?.end??0)+1,Math.min(config.windows[i+1]?.end-1||2000,val));point.style.left=`${w.end/zoom*100}%`;point.firstChild.textContent=w.end;};point.onpointerup=()=>{save();renderWindows();updateSummary();};axis.append(point);}start=w.end;}axis.insertAdjacentHTML('beforeend',`<span class="axis-origin">0 ms</span><span class="axis-end">${zoom} ms → ∞</span>`);
$('#windows').replaceChildren(...config.windows.map((w,i)=>{const row=document.createElement('div');row.className='window-row';const swatch=document.createElement('span');swatch.className='swatch';swatch.style.setProperty('--c',colors[i%colors.length]);const name=document.createElement('input');name.value=w.name;name.maxLength=20;name.setAttribute('aria-label',`区间 ${i+1} 名称`);name.onchange=()=>{w.name=name.value.trim()||`LEVEL ${i+1}`;save();renderWindows();};const end=document.createElement('input');end.type='number';end.value=w.end;end.min=(config.windows[i-1]?.end??0)+1;end.max=config.windows[i+1]?.end-1||2000;end.setAttribute('aria-label',`区间 ${i+1} 端点毫秒`);end.onchange=()=>{w.end=Math.max(Number(end.min),Math.min(Number(end.max),Math.round(Number(end.value)||Number(end.min))));save();renderWindows();updateSummary();};const del=document.createElement('button');del.title='删除端点';del.innerHTML='<i data-lucide="x"></i>';del.disabled=config.windows.length===1;del.onclick=()=>{config.windows.splice(i,1);save();renderWindows();updateSummary();};row.append(swatch,name,end,del);return row;}));const tail=document.createElement('p');tail.className='tail';tail.textContent=`${config.windows.at(-1).end} ms → +∞`;$('#windows').append(tail);iconize();}
$('#zoom').oninput=renderWindows;$('#add-boundary').onclick=()=>{const end=Math.round(Number($('#new-boundary').value));if(end<1||end>2000||config.windows.some(w=>w.end===end))return showError('端点需为 1–2000 ms 内不重复的整数');config.windows.push({end,name:'NEW'});config.windows.sort((a,b)=>a.end-b.end);showError();save();renderWindows();updateSummary();};
function renderBindings(){$('#bindings').replaceChildren(...config.keys.map((key,i)=>{const button=document.createElement('button');button.innerHTML=`<small>LANE ${i+1}</small><span>${captureKey===i?'按下新键':keyName(key)}</span>`;button.onclick=()=>{captureKey=i;renderBindings();};return button;}));positionLabels();}
function initializeControls(){for(const id of ['repeat','bpm','speed','slope','wingAngle','offset','volume']){$('#'+id).value=config[id];$('#'+id).oninput=()=>{const el=$('#'+id);if(!el.checkValidity())return;config[id]=Number(el.value);save();updateSummary();if(id==='slope'||id==='wingAngle')updateTrack();};$('#'+id).onchange=()=>{const el=$('#'+id);if(!el.checkValidity()||!el.value)el.value=config[id];};}for(const id of ['sound','hitSound','metronome']){$('#'+id).checked=config[id];$('#'+id).onchange=e=>{config[id]=e.target.checked;save();};}$('#division').replaceChildren(...[4,8,16,32].map(n=>{const b=document.createElement('button');b.textContent=`1/${n}`;b.classList.toggle('active',config.division===n);b.onclick=()=>{config.division=n;save();initializeControls();updateSummary();};return b;}));renderBindings();renderWindows();updateTrack();changed();}
const transposeLabel=document.createElement('label');transposeLabel.className='field';transposeLabel.textContent='重复移调';const transposeSelect=document.createElement('select');transposeSelect.innerHTML='<option value="diatonic">C 大调逐级</option><option value="whole">固定全音</option>';transposeSelect.value=config.transpose;transposeSelect.onchange=()=>{config.transpose=transposeSelect.value;save();};transposeLabel.append(transposeSelect);$('#tab-keys').insertBefore(transposeLabel,$('#reset'));
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{captureKey=-1;document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab-content').forEach(x=>x.hidden=x.id!==`tab-${b.dataset.tab}`);showError();});
$('#reset').onclick=()=>{config=structuredClone({...defaults,transpose:'diatonic'});transposeSelect.value=config.transpose;initializeControls();};

function ensureAudio(){audio??=new AudioContext();return audio.resume();}
function tone(midi,when,length=.17,volume=1){if(!audio||when<audio.currentTime-.03)return;const freq=440*2**((midi-69)/12);if(freq>18000)return;const g=audio.createGain();g.connect(audio.destination);const start=Math.max(when,audio.currentTime);g.gain.setValueAtTime(0,start);g.gain.linearRampToValueAtTime(config.volume*.16*volume,start+.004);g.gain.exponentialRampToValueAtTime(.0001,start+length);for(const [multiple,level] of [[1,1],[2,.26],[3,.07]]){const osc=audio.createOscillator(),partial=audio.createGain();osc.type='sine';osc.frequency.value=freq*multiple;partial.gain.value=level;osc.connect(partial);partial.connect(g);osc.start(start);osc.stop(start+length+.02);voices.push(osc);osc.onended=()=>{osc.disconnect();partial.disconnect();voices=voices.filter(v=>v!==osc);};}setTimeout(()=>g.disconnect(),Math.max(0,(start+length-audio.currentTime)*1000+100));}
function stopAudio(){for(const voice of voices){try{voice.stop();}catch{}}voices=[];}
function scheduleMusic(){if(mode!=='playing'||manual)return;while(musicIndex<chart.notes.length&&chart.notes[musicIndex].time<elapsed+160){const n=chart.notes[musicIndex++];if(config.sound&&n.time>=elapsed-30)tone(n.midi,audioZero+n.time/1000,Math.max(.09,Math.min(.5,chart.step/1000*1.6)));}if(config.metronome){const beat=60000/config.bpm;while(2500+beatIndex*beat<elapsed+160){const t=2500+beatIndex*beat;if(t>=elapsed-30)tone(beatIndex%4===0?96:89,audioZero+t/1000,.04,.32);beatIndex++;}}}
function syncAudio(){audioZero=audio.currentTime-elapsed/1000;musicIndex=chart.notes.findIndex(n=>n.time>=elapsed);if(musicIndex<0)musicIndex=chart.notes.length;beatIndex=Math.max(0,Math.ceil((elapsed-2500)/(60000/config.bpm)));}
function clearMeshes(){for(const mesh of noteMeshes.values())world.remove(mesh);noteMeshes.clear();}
async function start(){if(!config.queue.length)return;showError();try{await ensureAudio();}catch{return showError('浏览器无法启用音频，请重试');}stopAudio();chart=makeChart(data,config);elapsed=0;manual=false;anchor=performance.now();mode='playing';combo=0;maxCombo=0;weight=0;counts=Array(config.windows.length+1).fill(0);errors=[];resolved=0;held.clear();flashes.fill(0);clearMeshes();$('#effects').replaceChildren();$('#setup').hidden=true;$('#overlay').hidden=true;$('#hud').hidden=false;document.body.classList.add('playing');syncAudio();resize();updateHUD();}
function pause(){if(mode!=='playing'&&mode!=='resuming')return; if(mode==='playing'&&!manual)elapsed=performance.now()-anchor;mode='paused';pausedAt=elapsed;stopAudio();held.clear();flashes.fill(0);$('#countdown').textContent='';$('#overlay').hidden=false;$('#modal-title').textContent='暂停练习';$('#modal-tag').textContent='SESSION PAUSED';$('#results').replaceChildren();$('#resume').hidden=false;}
async function resume(){await ensureAudio();mode='resuming';resumeUntil=performance.now()+1500;$('#overlay').hidden=true;}
function back(){mode='setup';stopAudio();held.clear();flashes.fill(0);clearMeshes();$('#setup').hidden=false;$('#hud').hidden=true;$('#overlay').hidden=true;$('#countdown').textContent='';$('#effects').replaceChildren();document.body.classList.remove('playing');resize();}
function effect(lane,name,color,error){const p=project(lane,0,.4);const e=document.createElement('div');e.className='hit-text';e.style.left=`${(p.x+1)*innerWidth/2}px`;e.style.top=`${(1-p.y)*innerHeight/2}px`;e.style.color=color;e.textContent=name;if(error!==null){const s=document.createElement('small');s.textContent=`${error>0?'+':''}${Math.round(error)} ms`;e.append(s);}$('#effects').append(e);e.onanimationend=()=>e.remove();}
function resolve(note,index,error=null){note.done=true;resolved++;counts[index<0?config.windows.length:index]++;if(index<0){combo=0;effect(note.lane,'MISS','#ff8f9b',null);}else{if(config.hitSound)tone(note.midi-12,audio.currentTime,.22);combo++;maxCombo=Math.max(combo,maxCombo);weight+=Math.max(0,1-Math.abs(error)/config.windows.at(-1).end);errors.push(error);effect(note.lane,config.windows[index].name,colors[index%colors.length],error);}const mesh=noteMeshes.get(note);if(mesh){world.remove(mesh);noteMeshes.delete(note);}updateHUD();}
function hit(lane){flashes[lane]=1;if(mode!=='playing')return;if(!manual)elapsed=performance.now()-anchor;expire();const time=elapsed-config.offset;const candidate=chart.notes.find(n=>!n.done&&n.lane===lane);if(!candidate)return;const error=time-candidate.time;const index=judge(error,config.windows);if(index>=0)resolve(candidate,index,error);}
function expire(){const limit=config.windows.at(-1).end;for(const n of chart.notes){if(n.time>=elapsed-config.offset-limit)break;if(!n.done)resolve(n,-1);}}
function updateHUD(){$('#score').textContent=String(Math.round(weight/Math.max(1,chart.notes.length)*1000000)).padStart(7,'0');$('#accuracy').textContent=`${(resolved?weight/resolved*100:100).toFixed(2)}%`;$('#combo').innerHTML=combo>1?`${combo}<small>COMBO</small>`:'';$('#progress div').style.width=`${Math.min(100,elapsed/chart.end*100)}%`;const section=chart.sections.findLast(s=>s.time<=elapsed)||chart.sections[0];$('#current').textContent=`HANON ${section.id.padStart(2,'0')}`;$('#phase').textContent=`${section.direction==='up'?'上行':'下行'} · ${section.repeat} / ${config.repeat} · ${config.bpm} BPM`;}
function finish(){mode='results';stopAudio();held.clear();$('#overlay').hidden=false;$('#modal-title').textContent='练习完成';$('#modal-tag').textContent='SESSION COMPLETE';$('#resume').hidden=true;const results=$('#results');results.replaceChildren();const score=document.createElement('div');score.className='result-score';score.textContent=String(Math.round(weight/chart.notes.length*1000000)).padStart(7,'0');results.append(score);const rows=[['准确率',`${(weight/chart.notes.length*100).toFixed(2)}%`],['最大连击',maxCombo],...config.windows.map((w,i)=>[w.name,counts[i]]),['MISS',counts.at(-1)],['平均偏差',errors.length?`${(errors.reduce((a,b)=>a+b,0)/errors.length).toFixed(1)} ms`:'—']];for(const [name,value]of rows){const row=document.createElement('div');row.className='result-row';const label=document.createElement('span'),v=document.createElement('span');label.textContent=name;v.textContent=value;row.append(label,v);results.append(row);}}
$('#start').onclick=start;$('#pause').onclick=pause;$('#resume').onclick=resume;$('#restart').onclick=start;$('#back').onclick=back;$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>showError('当前浏览器不支持全屏'));};
addEventListener('keydown',e=>{if(captureKey>=0){e.preventDefault();if(e.code==='Escape'){captureKey=-1;renderBindings();return;}if(['Escape','Tab','MetaLeft','MetaRight'].includes(e.code)||e.metaKey||e.ctrlKey||e.altKey)return;if(config.keys.includes(e.code)&&config.keys[captureKey]!==e.code)return showError('该按键已分配给其他轨道');config.keys[captureKey]=e.code;captureKey=-1;showError();save();renderBindings();return;}if(e.code==='Escape'){e.preventDefault();if(mode==='playing'||mode==='resuming')pause();else if(mode==='paused')resume();return;}if(e.target.matches('input,select,textarea'))return;const lane=config.keys.indexOf(e.code);if(lane<0)return;e.preventDefault();if(e.repeat||held.has(e.code))return;held.add(e.code);hit(lane);});
addEventListener('keyup',e=>held.delete(e.code));addEventListener('blur',()=>{held.clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
const raycaster=new THREE.Raycaster();renderer.domElement.style.touchAction='none';renderer.domElement.addEventListener('pointerdown',e=>{if(mode!=='playing')return;raycaster.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);const hits=raycaster.intersectObjects(receptors);if(hits.length)hit(receptors.indexOf(hits[0].object));else{let best=0,d=Infinity;for(let i=0;i<6;i++){const p=project(i);const dist=Math.abs(e.clientX-(p.x+1)*innerWidth/2);if(dist<d){d=dist;best=i;}}hit(best);}});
function render(){const preview=mode==='setup';if(preview){clearMeshes();for(let i=0;i<12;i++){const lane=[0,2,3,4,5,4,3,2][i%8],mesh=new THREE.Mesh(noteGeo,noteMaterials[lane]);mesh.rotation.z=lane===0?-THREE.MathUtils.degToRad(config.wingAngle):lane===5?THREE.MathUtils.degToRad(config.wingAngle):0;const z=-((i*3.5+performance.now()/1600)%44)-3;mesh.position.set(lane-2.5,height(lane-2.5)+.075,z);world.add(mesh);noteMeshes.set(i,mesh);}}else if(chart){for(const n of chart.notes){if(n.done)continue;const z=-(n.time-elapsed)/1000*config.speed;if(z< -58)break;if(z>5)continue;let mesh=noteMeshes.get(n);if(!mesh){mesh=new THREE.Mesh(noteGeo,noteMaterials[n.lane]);mesh.rotation.z=n.lane===0?-THREE.MathUtils.degToRad(config.wingAngle):n.lane===5?THREE.MathUtils.degToRad(config.wingAngle):0;world.add(mesh);noteMeshes.set(n,mesh);}mesh.position.set(n.lane-2.5,height(n.lane-2.5)+.075,z);}}for(let i=0;i<6;i++){flashes[i]*=.9;lit[i].material.opacity=held.has(config.keys[i])?.38:flashes[i]*.4;}renderer.render(scene,camera);}
function tick(){if(mode==='playing'){if(!manual)elapsed=performance.now()-anchor;expire();scheduleMusic();updateHUD();$('#countdown').textContent=elapsed<2500?String(Math.ceil((2500-elapsed)/1000)):'';if(elapsed>chart.end+Math.max(0,config.offset))finish();}else if(mode==='resuming'){$('#countdown').textContent=String(Math.ceil((resumeUntil-performance.now())/1000));if(performance.now()>=resumeUntil){mode='playing';elapsed=pausedAt;anchor=performance.now()-elapsed;syncAudio();}}render();requestAnimationFrame(tick);}
window.render_game_to_text=()=>JSON.stringify({mode,time:elapsed,coordinateSystem:'lanes 0–5 left to right; z=0 judgement; negative z away; error=input time minus target time',score:Math.round(weight/Math.max(1,chart?.notes.length||1)*1000000),combo,maxCombo,resolved,counts,windows:config.windows,queue:config.queue,total:chart?.notes.length||0,notes:chart?.notes.filter(n=>!n.done&&n.time<elapsed+4000).slice(0,32).map(n=>({lane:n.lane,time:n.time,midi:n.midi}))||[],audio:{state:audio?.state,scheduled:musicIndex,voices:voices.length},keys:config.keys});
window.advanceTime=ms=>{manual=true;stopAudio();if(mode==='playing'){elapsed+=ms;expire();updateHUD();if(elapsed>chart.end+Math.max(0,config.offset))finish();}render();};
initializeControls();resize();iconize();tick();
