export const SPEED_SCALE=10.5;
export const defaults={queue:['1','2','3'],repeat:2,bpm:75,division:16,speed:42,slope:10,wingAngle:30,judgementZ:0,farDistance:58,musicVolume:1,hitVolume:1,earlyProtection:120,missName:'BREAK',extraColors:[],keys:['ShiftLeft','KeyA','KeyS','KeyD','KeyF','Space'],windows:[{end:25,name:'EXACT+'},{end:50,name:'EXACT'},{end:100,name:'NEAR'}],offset:0,sound:true,hitSound:true,metronome:false,volume:.3};
export const tierColors={brightPurple:'#edb0ff',purple:'#b178ff',teal:'#39daca',red:'#ff586e'};
export function judgementColors(total,extras=[]){const {brightPurple,purple,teal,red}=tierColors;if(total===2)return [purple,red];if(total===3)return [purple,teal,red];return [brightPurple,purple,...extras.slice(0,Math.max(0,total-4)),teal,red];}
export function parseUnit(unit){if(!/^(?:[1-6]|\([1-6]+\))+$/.test(unit))throw Error('无效谱面数字串');return unit.match(/\([1-6]+\)|[1-6]/g).map(token=>[...new Set(token.replace(/[()]/g,'').split('').map(n=>Number(n)-1))]);}
export function pitch(lane,shift,mode='diatonic'){const scale=[0,2,4,5,7,9,11];const degree=lane+(mode==='whole'?0:shift);return 60+scale[((degree%7)+7)%7]+12*Math.floor(degree/7)+(mode==='whole'?shift*2:0);}
export function makeChart(data,config){const step=60000/config.bpm*4/config.division;const start=Math.max(2500,((config.farDistance??58)+(config.judgementZ??0))/config.speed*1000+500);let time=start;const notes=[];const sections=[];for(const id of config.queue){for(const direction of ['up','down']){for(let r=0;r<config.repeat;r++){const shift=direction==='up'?r:config.repeat-1-r;sections.push({time,id,direction,repeat:r+1,shift});for(const lanes of parseUnit(data[id][direction])){for(const lane of lanes)notes.push({time,lane,midi:pitch(lane,shift,config.transpose),id,direction,repeat:r+1,done:false});time+=step;}}}}return {notes,sections,step,start,end:notes.length?time-step+Math.max(1000,config.windows.at(-1).end+100):0};}
export function judge(error,windows){return windows.findIndex(w=>Math.abs(error)<=w.end);}
// null ignores a press; -1 consumes the note as MISS; nonnegative values name hit tiers.
export function judgePress(error,windows,earlyProtection=null){const tier=judge(error,windows);if(tier>=0)return tier;const limit=windows.at(-1).end;if(error>limit)return -1;if(earlyProtection!==null&&error>=-earlyProtection)return -1;return null;}
