import {setLegacyWindows} from './legacy-windows.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('output/qa',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForFunction(()=>!!window.render_game_to_text);
await setLegacyWindows(page);
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
await page.screenshot({path:'output/qa/setup.png'});
await page.getByTitle('添加哈农 4',{exact:true}).click();assert.deepEqual((await state()).queue,['1','2','3','4']);
await page.locator('#queue li').last().getByTitle('上移').click();assert.deepEqual((await state()).queue,['1','2','4','3']);
await page.locator('#queue li').last().getByTitle('移除').click();
await page.locator('[data-tab="judge"]').click();await page.locator('#new-boundary').fill('200');await page.locator('#add-boundary').click();assert.equal((await state()).windows.at(-1).end,200);
await page.getByLabel('区间 4 名称',{exact:true}).fill('LATE');await page.getByLabel('区间 4 名称',{exact:true}).press('Tab');
await page.screenshot({path:'output/qa/judgements.png'});
await page.locator('#windows .window-row:not(.miss-row)').last().getByTitle('删除端点').click();
await page.locator('[data-tab="keys"]').click();await page.locator('#bindings button').first().click();await page.keyboard.press('q');assert.equal((await state()).keys[0],'KeyQ');
await page.reload();await page.waitForFunction(()=>!!window.render_game_to_text);assert.equal((await state()).keys[0],'KeyQ');
await page.locator('#bpm').fill('60');await page.locator('#division button').first().click();await page.locator('#repeat').fill('1');
await page.locator('#start').click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='playing');
await page.evaluate(()=>window.advanceTime(2359-JSON.parse(window.render_game_to_text()).time));await page.keyboard.press('q');assert.equal((await state()).resolved,0,'early press must be ignored');
await page.evaluate(()=>window.advanceTime(1));await page.keyboard.press('q');assert.equal((await state()).resolved,1,'-140 boundary must hit');
await page.evaluate(()=>window.advanceTime(1140));await page.keyboard.press('s');assert.equal((await state()).counts[0],1,'exact hit');
await page.evaluate(()=>window.advanceTime(1140));await page.keyboard.press('d');assert.equal((await state()).resolved,3,'+140 boundary must hit');
await page.evaluate(()=>window.advanceTime(1001));assert.equal((await state()).counts.at(-1),1,'late note auto misses');
await page.screenshot({path:'output/qa/gameplay.png'});
await page.keyboard.press('Escape');assert.equal((await state()).mode,'paused');const t=(await state()).time;await page.evaluate(()=>window.advanceTime(300));assert.equal((await state()).time,t);await page.screenshot({path:'output/qa/pause.png'});
await page.locator('#resume').click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='playing');assert.equal((await state()).time,t);await page.evaluate(()=>window.advanceTime(1000000));assert.equal((await state()).mode,'results');assert.equal((await state()).resolved,(await state()).total);await page.screenshot({path:'output/qa/results.png'});
await page.locator('#restart').click();await page.waitForTimeout(2900);const playing=await state();assert.equal(playing.audio.state,'running');assert.ok(playing.audio.scheduled>0,'music must schedule without key presses');
await page.keyboard.press('Escape');await page.locator('#back').click();
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/qa/mobile-setup.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
await page.locator('#start').click();await page.evaluate(()=>window.advanceTime(1800));await page.screenshot({path:'output/qa/mobile-game.png'});
assert.equal(await page.locator('#lane-labels span').count(),6);for(const box of await page.locator('#lane-labels span').all()){const b=await box.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=390&&b.y>=0&&b.y+b.height<=844,'mobile receptor label in viewport');}
const pixels=await page.evaluate(()=>{window.advanceTime(0);const c=document.querySelector('canvas'),g=c.getContext('webgl2');const a=new Uint8Array(4*c.width*c.height);g.readPixels(0,0,c.width,c.height,g.RGBA,g.UNSIGNED_BYTE,a);return new Set(Array.from(a)).size;});assert.ok(pixels>8,'canvas nonblank');
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,musicScheduled:playing.audio.scheduled,canvasPixelValues:pixels,errors}));await browser.close();
