import {setLegacyWindows} from './legacy-windows.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
await fs.mkdir('output/protection',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.waitForFunction(()=>!!window.render_game_to_text);
await setLegacyWindows(page);
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
assert.equal((await state()).worldSpeed,42);assert.equal((await state()).speed,4);
await page.locator('#speed').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#speed-number').inputValue(),'4.01');assert.equal((await state()).worldSpeed,42.105);
await page.locator('#speed-number').fill('5.23');await page.locator('#speed-number').press('Tab');assert.equal((await state()).worldSpeed,54.915);
await page.evaluate(()=>{const c=JSON.parse(localStorage.getItem('hanon-six'));c.speed=52.5;c.slope=22;c.wingAngle=40;localStorage.setItem('hanon-six',JSON.stringify(c));});await page.reload();await page.waitForFunction(()=>!!window.render_game_to_text);assert.equal(await page.locator('#speed-number').inputValue(),'5.00');assert.equal((await state()).worldSpeed,52.5);
await page.locator('[data-default="speed"]').click();assert.equal((await state()).worldSpeed,42);assert.equal((await state()).slope,22);assert.equal((await state()).wingAngle,40);
await page.locator('[data-default="slope"]').click();assert.equal((await state()).slope,10);assert.equal((await state()).wingAngle,40);
await page.locator('[data-default="wingAngle"]').click();assert.equal((await state()).wingAngle,30);
await page.screenshot({path:'output/protection/defaults.png',fullPage:true});
await page.locator('#bpm').fill('60');await page.locator('#division button').first().click();
await page.locator('[data-tab="judge"]').click();await page.locator('#early-enabled').check();assert.equal((await state()).earlyProtection,200);
let marker=await page.locator('.protection-point').boundingBox();const axis=await page.locator('#axis').boundingBox();await page.mouse.move(marker.x+marker.width/2,marker.y+marker.height/2);await page.mouse.down();await page.mouse.move(axis.x+axis.width*220/300,marker.y+marker.height/2);await page.mouse.up();assert.ok(Math.abs((await state()).earlyProtection-220)<=1);
await page.locator('#new-boundary').fill('250');await page.locator('#add-boundary').click();assert.equal((await state()).earlyProtection,251);await page.locator('#early-point').fill('100');await page.locator('#early-point').press('Tab');assert.equal((await state()).earlyProtection,251);
await page.locator('#windows .window-row:not(.miss-row)').last().getByTitle('删除端点').click();await page.locator('#early-point').fill('200');await page.locator('#early-point').press('Tab');
await page.screenshot({path:'output/protection/axis.png',fullPage:true});
await page.reload();await page.waitForFunction(()=>!!window.render_game_to_text);assert.equal((await state()).earlyProtection,200);
await page.locator('[data-tab="keys"]').click();await page.locator('#sound').uncheck();
await page.locator('#start').click();await page.waitForFunction(()=>JSON.parse(window.render_game_to_text()).mode==='playing');
const jump=t=>page.evaluate(t=>window.advanceTime(t-JSON.parse(window.render_game_to_text()).time),t);
await jump(2299);await page.keyboard.press('ShiftLeft');assert.equal((await state()).resolved,0,'outside -x ignored');
await jump(2300);await page.keyboard.press('ShiftLeft');assert.equal((await state()).counts.at(-1),1,'-x consumes early note as MISS');assert.equal((await state()).audio.voices,0,'early MISS has no hit tone');assert.equal((await state()).notes.some(n=>n.time===2500),false);
await jump(3360);await page.keyboard.press('s');assert.equal((await state()).counts[2],1,'-140 inclusive');
await jump(4640);await page.keyboard.press('d');assert.equal((await state()).counts[2],2,'+140 inclusive');
await jump(5641);assert.equal((await state()).counts.at(-1),2,'auto miss before +x');await jump(5701);assert.equal((await state()).counts.at(-1),2,'no second miss after +x');
await jump(6359);await page.keyboard.press('Space');assert.equal((await state()).counts.at(-1),3,'-141 early miss');await page.screenshot({path:'output/protection/game.png'});
await page.keyboard.press('Escape');await page.locator('#back').click();await page.locator('[data-tab="judge"]').click();await page.locator('#early-enabled').uncheck();assert.equal((await state()).earlyProtection,null);assert.equal(await page.locator('.protection-point').count(),0);
await page.locator('#start').click();await jump(2359);await page.keyboard.press('ShiftLeft');assert.equal((await state()).resolved,0,'disabled protection preserves old early-ignore behavior');
await page.keyboard.press('Escape');await page.locator('#back').click();await page.locator('#early-enabled').check();await page.setViewportSize({width:390,height:844});await page.screenshot({path:'output/protection/mobile-axis.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,errors}));await browser.close();
